//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by texsetup.rc
//
#define IDM_ABOUTBOX                    0x0010
#define IDD_ABOUTBOX                    100
#define IDS_ABOUTBOX                    101
#define IDD_PROPPAGE_UNINSTALL          102
#define IDP_SOCKETS_INIT_FAILED         103
#define IDS_PROPSHT_CAPTION             104
#define IDS_LOCAL_GUIDE                 105
#define IDD_PROPPAGE_WELCOME            105
#define IDS_LATEX2E_REFERENCE           106
#define IDD_PROPPAGE_ROOT               106
#define IDS_DVI_VIEWER                  107
#define IDD_PROPPAGE_SETUP_STYLE        107
#define IDD_PROPPAGE_SCHEME             107
#define IDS_MAINTENANCE                 108
#define IDD_PROPPAGE_CUSTOM_DIRS        108
#define IDS_CREATE_ALL_FORMATS_FILES    109
#define IDD_PROPPAGE_PACKAGES           109
#define IDS_CREATE_ALL_FORMAT_FILES     109
#define IDS_REFRESH_FILENAME_DATABASE   110
#define IDD_PROPPAGE_REVIEW             110
#define IDS_CREATE_LATEX_FORMAT_FILE    111
#define IDS_HELP                        112
#define IDS_FAQ                         113
#define IDD_PROPPAGE_FILE_COPY          113
#define IDS_LICENSE                     114
#define IDD_PROPPAGE_ERROR              114
#define IDS_WELCOME_LICENSE             114
#define IDS_FAILED_GET_DIRECTORY        115
#define IDD_PROPPAGE_SUPPLEMENT         115
#define IDS_CANCEL_SETUP                116
#define IDD_PROPPAGE_REBOOT             116
#define IDS_FILECOPY_COMPLETED          117
#define IDD_PROPPAGE_CONFIG             117
#define IDS_CANT_COPY_FILE              118
#define IDD_PROPPAGE_SOURCE             118
#define IDS_CANT_OPEN_LOGFILE           119
#define IDS_ERROR_UNZIPPING             120
#define IDS_NOW_INSTALLING              121
#define IDS_NOW_UNZIPPING               122
#define IDS_NOW_DOWNLOADING             123
#define IDS_CANNOT_INSTALL_SHARED_FILE  124
#define IDS_CANNOT_CREATE_TEMPFILE      125
#define IDS_CANNOT_MOVE_FILE            126
#define IDS_CANNOT_CREATE_RUNONCE_VALUE 127
#define IDS_CONFIGURATION_COMPLETED     128
#define IDR_MAINFRAME                   128
#define IDS_TPM_FILES_READ              129
#define IDS_CREATE_MISSING_FORMAT_FILES 130
#define IDS_TEXSHELL_EDITOR             131
#define IDB_INTERNET                    131
#define IDS_PFE_EDITOR                  132
#define IDS_XEMACS_EDITOR               133
#define IDS_XEMACS_HELP                 134
#define IDS_PFE_HELP                    135
#define IDS_TEXSHELL_HELP               136
#define IDS_UNINSTALL                   137
#define IDS_REMOTE_GUIDE                138
#define IDS_TUG_GUIDE                   139
#define IDB_LION_MINI                   140
#define IDS_UNINSTALL_COMPLETED         140
#define IDB_DONE                        141
#define IDS_UNINSTALL_PROMPT            141
#define IDS_PREVIOUS_SETUP_DETECTED     142
#define IDB_PART_CHECKED                143
#define IDS_UNINSTALL_WARNING           143
#define IDB_FAILED                      144
#define IDS_ADD_PACKAGE                 144
#define IDS_LICENSE_FPTEX               145
#define IDB_TREE_BOXES                  146
#define IDS_CAPTION                     146
#define IDB_TEXSETUP                    147
#define IDS_CAPTION_FPTEX               147
#define IDS_TOOLTIP_QUICKINSTALL        148
#define IDS_TOOLTIP_ADMINISTRATOR       149
#define IDI_TEXSETUP                    149
#define IDS_CONFIGURATION_ERROR         150
#define IDD_DIALOG_TPM_PROGRESS         151
#define IDS_FILECOPY_ERROR              151
#define IDI_ICON_UNINSTALL              152
#define IDI_UNINSTALL                   152
#define IDS_CANNOT_RUN_PROCESS          152
#define IDS_CANT_GRAB_TPM_INTERNET      153
#define IDS_CANT_UNZIP_TPM              154
#define IDD_PROPPAGE_GETTPM             154
#define IDS_NOW_PARSING                 155
#define IDD_DIALOG_LIST_CHOICE          155
#define IDS_CANT_READ_TPM_FILES         156
#define IDS_WELCOME_MAINTENANCE         157
#define IDB_BITMAP1                     157
#define IDS_UNINSTALL_FILES_NOT_REMOVED 158
#define IDS_CLICK_FINISH                159
#define IDS_CLICK_REBOOT                160
#define IDB_BITMAP2                     160
#define IDB_CONNECT                     160
#define IDS_REBOOT_COMPUTER             161
#define IDI_ICON1                       161
#define IDS_WELCOME_QUICK               162
#define IDS_OVERALL_DOWNLOADING         163
#define IDS_OVERALL_UNZIPPING           164
#define IDS_NOW_REMOVING                165
#define IDS_TOOLTIP_XEMTEX              166
#define IDC_EDIT_SUMMARY                1000
#define IDC_EXTRA_TEXMF                 1001
#define IDC_VAR_TEXMF                   1002
#define CG_IDC_PROGDLG_PROGRESS_PACKAGE 1003
#define IDC_LOCAL_TEXMF                 1004
#define IDC_STATIC_PERCENT_PACKAGE      1004
#define IDC_HOME_TEXMF                  1005
#define IDC_STATIC_PERCENT_UNIT         1005
#define IDC_VAR_FONTS                   1006
#define CG_IDC_PROGDLG_PROGRESS_TOTAL   1006
#define IDC_CHECK_WINEDT                1007
#define IDC_STATIC_PERCENT_TOTAL        1007
#define IDC_CHECK_IMAGICK               1008
#define IDC_STATIC_PERCENT_UNIT2        1008
#define IDC_ROOTDIR                     1009
#define IDC_CHECK_TEXSHELL              1009
#define IDC_CHECK_GHOST                 1010
#define IDC_CHECK_GS550                 1010
#define IDC_CHECK_WINSHELL              1011
#define IDC_BASIC_INSTALL               1012
#define IDC_REC_INSTALL                 1013
#define IDC_TREE_PACKAGES               1013
#define IDC_FULL_INSTALL                1014
#define IDC_BROWSE                      1014
#define IDC_CUSTOM_INSTALL              1015
#define IDC_EDIT_LICENSE                1015
#define IDC_STATIC_SPACE_AVAILABLE      1016
#define IDC_CHECK_ADMINISTRATOR         1018
#define IDC_CHECK_QUICKINSTALL          1019
#define IDC_CHECK_NETPBM                1020
#define IDC_CHECK_NTEMACS               1021
#define IDC_CHECK_GS60                  1022
#define IDC_CHECK_PSUTILS               1023
#define IDC_CHECK_PFE                   1024
#define IDC_CHECK_SOURCE                1025
#define IDC_CHECK_DOC                   1026
#define IDC_CHECK_VIEW_LOGFILE          1026
#define IDC_EDIT_ERROR                  1027
#define IDC_PROMPT                      1028
#define IDC_LOGFILE                     1029
#define IDC_STATIC_PACKAGE_SIZE         1030
#define IDC_STATIC_TOTAL_SIZE           1031
#define IDC_STATIC_HEADER               1033
#define IDC_STATIC_INSTALLING_COLLECTION 1034
#define IDC_STATIC_TOTAL                1035
#define IDC_STATIC_COLLECTION           1036
#define IDC_STATIC_DEFAULT_SIZE         1037
#define IDC_STATIC_PACKAGE              1037
#define IDC_STATIC_INSTALLING_PACKAGE   1038
#define IDC_CHECK_REBOOT                1039
#define IDC_STATIC_INSTALLING           1040
#define IDC_EDIT_DESCRIPTION            1041
#define IDC_CHECK_FRENCH                1042
#define IDC_STATIC_LOGNAME              1043
#define IDC_PROGRESS_TPM                1044
#define IDC_STATIC_READING              1045
#define IDC_CHECK_PERL                  1049
#define IDC_CHECK_TEXNICCENTER          1049
#define IDC_STATIC_NET_DOWNLOAD         1050
#define IDC_STATIC_REBOOT               1051
#define IDC_CHECK_PERL2                 1051
#define IDC_CHECK_XEMACS                1052
#define IDC_CHECK_LOG                   1053
#define IDC_CHECK_LATEX2HTML            1053
#define IDC_STATIC_ADMIN                1054
#define IDC_STATIC_LOCAL                1055
#define IDC_RADIO_CDROM                 1056
#define IDC_CDROM_INSTALL               1056
#define IDC_EDIT_HOMEDIR                1057
#define IDC_STATIC_HOMEDIR              1058
#define IDC_OK_SUPP                     1059
#define IDC_OK_LSR                      1060
#define IDC_OK_FORMAT                   1061
#define IDC_OK_DLLS                     1062
#define IDC_OK_ENVIRONMENT              1063
#define IDC_OK_SHELL                    1064
#define IDC_STATIC_SUPP                 1065
#define IDC_STATIC_LSR                  1066
#define IDC_STATIC_FORMAT               1067
#define IDC_STATIC_DLLS                 1068
#define IDC_STATIC_ENVIRONMENT          1069
#define IDC_STATIC_SHELL                1070
#define IDC_STATIC_FILES                1071
#define IDC_STATIC_MENU                 1072
#define IDC_OK_FILES                    1073
#define IDC_OK_MENU                     1074
#define IDC_OK_REGISTRY                 1075
#define IDC_STATIC_REGISTRY             1076
#define IDC_STATIC_RMDIR                1077
#define IDC_CHECK_NETDOWNLOAD           1078
#define IDC_EDIT_SOURCE_DIR             1079
#define IDC_RADIO_SOURCE_LOCAL          1080
#define IDC_RADIO_SOURCE_CDROM          1080
#define IDC_RADIO_SOURCE_LOCAL_INTERNET 1081
#define IDC_RADIO_SOURCE_ZIP            1081
#define IDC_INTERNET_CONNECTION_IE5     1082
#define IDC_INTERNET_CONNECTION_DIRECT  1083
#define IDC_INTERNET_CONNECTION_PROXY   1084
#define IDC_EDIT_PROXY_PORT             1085
#define IDC_EDIT_PROXY_ADDRESS          1086
#define IDC_BROWSE_LOCAL                1088
#define IDC_EDIT_REMOTE_DIR             1089
#define IDC_RADIO_SOURCE_INTERNET       1090
#define IDC_BROWSE_REMOTE               1091
#define IDC_STATIC_TPM_NAME             1092
#define IDC_CHECK_CUSTOM_DIRS           1094
#define IDC_STATIC_DOWNLOADING          1095
#define CG_IDC_PROGDLG_PROGRESS_DOWNLOAD 1096
#define CG_IDC_PROGDLG_PROGRESS_READ    1097
#define IDC_STATIC_PERCENT_DOWNLOAD     1098
#define IDC_STATIC_TPMZIP               1099
#define IDC_STATIC_TPMREAD              1100
#define IDC_STATIC_DESCRIPTION          1100
#define IDC_COMBO_LIST_CHOICE           1101
#define IDC_LISTCHOICE_RADIO1           1102
#define IDC_LISTCHOICE_RADIO2           1103
#define IDC_LISTCHOICE_RADIO3           1104
#define IDC_STATIC_MESSAGE              1105
#define IDC_STATIC_EXPLANATION          1106
#define IDC_LIST_SCHEME                 1109
#define IDC_STATIC_SCHEME               1110
#define IDC_CHECK_CUSTOMIZE_SCHEME      1111
#define IDC_CHECK1                      1112
#define IDC_CHECK_XEMTEX                1112

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        162
#define _APS_NEXT_COMMAND_VALUE         32771
#define _APS_NEXT_CONTROL_VALUE         1113
#define _APS_NEXT_SYMED_VALUE           116
#endif
#endif
