#! /bin/sh

# Script to stick bounding box finder in front of a postscript file
#    Adapted from Ned's original

# $Header: /home/xubuntu/berlios_backup/github/tmp-cvs/texlive/Repository/source.development/TeX/texk/dvipsk/contrib/bbfig/bbfig,v 1.1 2004/01/08 13:44:22 rahtz Exp $

# BBPSDIR=<wherever>  # Define this if bb.ps doesn't live in same
                      #   directory as bbfig

if [ ! -f ${BBPSDIR=`dirname $0`}/bb.ps ]
then
    echo >&2 "Can't locate bb.ps"
    exit 1
fi

case $# in
    0)    cat $BBPSDIR/bb.ps -
	  ;;
    *)    cat $BBPSDIR/bb.ps "$@"
	  ;;
esac
